---
abstract: 'Perl wrapper to librados.'
author:
  - 'Alex <alex@openimp.net>'
dynamic_config: 1
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v2.0.html
  version: '2.0'
name: Ceph-Rados
no_index:
  directory:
    - t
    - inc
prereqs:
  configure:
    requires:
      Devel::CheckLib: '0'
      ExtUtils::MakeMaker: '0'
version: '0.04'
